<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/public/css/style.css" />
    <script src="http://code.jquery.com/jquery-2.0.0.min.js"></script>
</head>
<body>
    <?php echo $this->content; ?>
    <script src="/public/js/map.js"></script>
    <script src="/public/js/robot.js"></script>
    <script src="/public/js/main.js"></script>
</body>
</html>
